// Generated by CoffeeScript 1.10.0
(function() {
  chrome.browserAction.onClicked.addListener(function() {
    return chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      console.log("send request");
      return chrome.tabs.sendMessage(tabs[0].id, "init", function(data) {
        return console.log("sendShowRequestDone", data);
      });
    });
  });

}).call(this);
